sudo: false # Explicitly use container-based infrastructure

language: go

go:
    - 1.6.1
    
env:
    global:
        - BUILDER_VERSION=0.11.0
    matrix:
        - TEST_SUITE=unit
        # We no longer run an integration test machine (16/10/16)
        # - TEST_SUITE=integration

cache:
    directories:
        - ./builder-cache

notifications:
    email: false

before_install:
    # Decrypt gitcookies and ssh key. The tarball contains `gitcookies` and `inago-integration-test.pem`.
    # We use a tarball here because of: https://github.com/travis-ci/travis.rb/issues/239
    - openssl aes-256-cbc -K "$encrypted_314659c9f31c_key" -iv "$encrypted_314659c9f31c_iv" -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - test -f ./gitcookies.sh && test -f ./inago-integration-test.pem
    
    # Set up the git http cookiefile, to avoid rate-limiting, see: https://github.com/golang/go/issues/12933
    - ./gitcookies.sh

    # Grab builder from the cache, or download it if we can't.
    - cp ./builder-cache/builder-$BUILDER_VERSION ./builder || wget https://downloads.giantswarm.io/builder/$BUILDER_VERSION/builder && chmod +x ./builder
    - chmod +x ./builder
    - export PATH=$PATH:$PWD
    - go get -u github.com/golang/lint/golint

script:
    - ./ci.sh

before_cache:
    - cp ./builder ./builder-cache/builder-$BUILDER_VERSION
