sudo: false # Explicitly use container-based infrastructure

language: go

go:
    - 1.6
    
env:
    global:
        - BUILDER_VERSION=0.11.0
    matrix:
        - TEST_SUITE=unit
        - TEST_SUITE=integration

cache:
    directories:
        - ./builder-cache

notifications:
    email: false

before_install:
    # Authenticate with googlesource, so we don't get ratelimited go-getting.
    # See: https://github.com/golang/go/issues/12933
    - ./gitcookies.sh
    # Decrypt the ssh key we use to communicate with the integration test server.
    # See: https://docs.travis-ci.com/user/encrypting-files/
    - openssl aes-256-cbc -K "$encrypted_314659c9f31c_key" -iv "$encrypted_314659c9f31c_iv" -in inago-integration-test.pem.enc -out ./inago-integration-test.pem -d
    # Grab builder from the cache, or download it if we can't.
    - cp ./builder-cache/builder-$BUILDER_VERSION ./builder || wget https://downloads.giantswarm.io/builder/$BUILDER_VERSION/builder && chmod +x ./builder
    - chmod +x ./builder
    - export PATH=$PATH:$PWD
    - go get -u github.com/golang/lint/golint

script:
    - ./ci.sh

before_cache:
    - cp ./builder ./builder-cache/builder-$BUILDER_VERSION
